### ISSUE TITLE
unable to get the three files required for data

### ISSUE THREAD

**Issue by anujshah1003** [iamaaditya/VQA_Keras#3]
how to get this three files
- 'data/data_prepro.json'
- 'data/data_img.h5'
- 'data/data_prepro.h5'

**Comment by iamaaditya** [comment]
See the links here https://github.com/VT-vision-lab/VQA_LSTM_CNN/blob/master/readme.md#evaluation

**Comment by anujshah1003** [comment]
do we need to have lua for that

**Comment by anujshah1003** [comment]
![image](https://cloud.githubusercontent.com/assets/20814689/19626765/ae1c596e-9955-11e6-80d0-024ba1ab591a.png)

i get this error

**Comment by iamaaditya** [comment]
Download the annotations from here http://visualqa.org/download.html
