### ISSUE TITLE
What is utils in this line? which library does it belong to?

### ISSUE THREAD

**Issue by jishnudantu** [iamaaditya/VQA_Keras#5]
https://github.com/iamaaditya/VQA_Keras/blob/0d58ddb9ea2bf6fc6900afe4a56344a5246c22b9/utils/get_data.py#L111

While running your code i keep getting an error at this line. could you explain what you are doing in that line and also could you direct me to the library utils is from?

**Comment by iamaaditya** [comment]
Hi

sorry, I don't know why the utils function never got included. The function most_common is this

```
def most_common(lst):
    return max(set(lst), key=lst.count)
```

See this for how to change it https://github.com/iamaaditya/VQA_Keras/commit/d6999208fa52d6259f98518027d99d813e05bb12
